---
scheme_version: 1
server_url: https://10.10.12.100
token: KentuckyHarvester
os:
  hostname: nuc-02
  ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCozGnmSeEzFQovxzvwgLaQmfE5/eGDfzKHMwofs1rvdef6WD89ubQjh2bFDe69IPGh0kV93QraLUXL1hDa3J+k9LIhr7HqAg365bm3UtY7jIDADmAjDo8yVJ5oiSMvmgUlaw3REFjaMXwQXCddDVWhoWFk/gE1w/14/EbFfSJni9iohl+A76s5GRlVZXSTVb/zYxeQFAlstUaxQVFD8EGNcWI5Ptydgil+hlrA7k16qrkj+5l5muDkRLndcsR/zrpLy2cdNWmI6s/aGQ/IHpUmLf92AAIbzMskK4Asdno1RiuNFybfjoPomo1NlYh6J/VS2uEq4Zg4zWuVbl7yjTRx mansible@kubernerd
  password: Passw0rd01
  ntp_servers:
    - 0.suse.pool.ntp.org
    - 1.suse.pool.ntp.org
    - 2.suse.pool.ntp.org
  dns_nameservers:
    - 10.10.12.9
    - 10.10.12.8
    - 8.8.8.8
install:
  skipchecks: true
  mode: join
  management_interface:
    interfaces:
      - name: enp86s0
    default_route: true
    method: static
    ip: 10.10.12.102
    subnet_mask: 255.255.252.0
    gateway: 10.10.12.1
  device: /dev/sda
  data_disk: /dev/nvme0n1
  #iso_url: http://10.10.12.8/harvester/v1.7.0/harvester-v1.7.0-amd64.iso
  iso_url: http://10.10.12.10/harvester/v1.7.1-amd64-govt.1/harvester-v1.7.1-govt.1-amd64.iso
